### ISSUE TITLE
.toggle crashes IE 10/11 Win7 VM

### ISSUE THREAD

**Issue by jfsiii** [necolas/dom-shims#3]
Tested in IE 10 & 11 on Win7 VM from https://github.com/xdissent/ievms

When the shim is in place, the path I saw was:
1. Call toggle in app code
2. Enter [DOMTokenListPrototype.toggle](https://github.com/necolas/dom-shims/blob/master/shim/Element.classList.js#L61)
3. Fall through to [else branch](https://github.com/necolas/dom-shims/blob/master/shim/Element.classList.js#L64)
4. Call [DOMTokenListPrototype.toggle](https://github.com/necolas/dom-shims/blob/master/shim/Element.classList.js#L65)
5. repeat steps 2-4 until "Out of stack space" error is thrown. 

If I bypass calls to `toggle`, using something like `el.classList[someTest ? 'add' : 'remove'](cssClass)`, no errors occur.

**Comment by necolas** [comment]
Fixed by https://github.com/necolas/dom-shims/commit/a31ada5ea2d05b8b732d1c2ca0e0add848a5dcd7
